name:  Deploy Autom치tico no Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name:  Limpar diret칩rio tempor치rio
        run: rm -rf /var/www/html/*

      - name:  Clonar reposit칩rio atualizado
        run: git clone https://github.com/Guilhermevitor044/meu-site-cicd.git /var/www/html

      - name:  Ajustar permiss칫es
        run: |
          chown -R www-data:www-data /var/www/html
          chmod -R 755 /var/www/html

      - name: 游대 Reiniciar Nginx
        run: systemctl reload nginx
